services:
  mysql:
    image: mysql:latest
    container_name: test_mysql
    hostname: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: jagan2911
      MYSQL_DATABASE: employeez
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3308:3306"
    volumes:
      - ./mysqldata/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -pjagan2911 -D employeez -e 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 40s
  
  
  chat-bot-1:
    image: chatbot:latest
    container_name: test_chatbot_1
    hostname: chatbot-server
    ports:
      - "8001:8000"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
    
  chat-bot-2:
    image: chatbot:latest
    container_name: test_chatbot_2
    hostname: chatbot-server
    ports:
      - "8002:8000"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chat-bot-1
      - chat-bot-2
    networks:
      - backend 
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

networks:
  backend:
    driver: bridge
    