services:
  mysql:
    image: mysql:latest
    container_name: test_mysql
    hostname: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: jagan2911
      MYSQL_DATABASE: employeez
    ports:
      - "3308:3306"
    volumes:
      - ./mysqldata/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 20s
  chat-bot:
    image: chat-bot:latest
    container_name: test_chatbot
    hostname: chatbot-server
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      mysql :
        condition: service_healthy
      

networks:
  backend:
    driver: bridge
    