services:
  mysql:
    image: mysql:latest
    container_name: test_mysql
    hostname: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: jagan2911
      MYSQL_DATABASE: employeez
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3308:3306"
    volumes:
      - ./mysqldata/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -pjagan2911 -D employeez -e 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 40s
  chat-bot:
    image: chat-bot:latest
    container_name: test_chatbot
    hostname: chatbot-server
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
networks:
  backend:
    driver: bridge
    